import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createPortal } from "react-dom";
const MEDAL = ["🥇", "🥈", "🥉"];
export function LeaderboardModal({ leaderboard, onClose }) {
    return createPortal(_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4", children: _jsxs("div", { className: "w-full max-w-sm rounded-2xl border border-white/10 bg-panel p-6 shadow-2xl", children: [_jsxs("div", { className: "mb-4 flex items-center justify-between", children: [_jsx("h2", { className: "font-display text-lg text-white", children: "\uD83C\uDFC6 Classement" }), _jsx("button", { type: "button", onClick: onClose, className: "text-slate-400 transition hover:text-white", children: "\u2715" })] }), leaderboard.length === 0 ? (_jsx("p", { className: "text-sm text-slate-500", children: "Aucun score pour le moment." })) : (_jsx("div", { className: "space-y-2", children: leaderboard.map((entry, i) => (_jsxs("div", { className: `flex items-center gap-3 rounded-xl px-3 py-2.5 ${i === 0 ? "border border-yellow-400/30 bg-yellow-400/10"
                            : i === 1 ? "border border-slate-400/20 bg-slate-400/10"
                                : i === 2 ? "border border-amber-600/20 bg-amber-600/10"
                                    : "border border-white/5 bg-ink/60"}`, children: [_jsx("span", { className: "w-6 text-center text-base", children: MEDAL[i] ?? _jsx("span", { className: "text-sm text-slate-500", children: i + 1 }) }), entry.user.avatar ? (_jsx("img", { src: entry.user.avatar, alt: "", className: "h-7 w-7 rounded-full object-cover" })) : (_jsx("span", { className: "flex h-7 w-7 items-center justify-center rounded-full bg-sky/20 text-xs font-bold text-sky", children: entry.user.username[0]?.toUpperCase() })), _jsx("span", { className: "flex-1 truncate text-sm font-medium text-slate-100", children: entry.user.username }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-sm font-semibold text-mint", children: [entry.score, " pts"] }), _jsxs("p", { className: "text-xs text-slate-500", children: [entry.wins, " victoire", entry.wins !== 1 ? "s" : ""] })] })] }, entry.id))) })), _jsx("button", { type: "button", onClick: onClose, className: "mt-4 w-full rounded-xl border border-white/10 py-2 text-sm text-slate-300 transition hover:bg-white/5", children: "Fermer" })] }) }), document.body);
}
